### ISSUE TITLE
input 事件触发

### ISSUE THREAD

**Issue by rehuhu** [qiuyaofan/datepicker#1]
选择日期后输入框填值了，通常怎么取值？input原来的事件在置值后都不触发了

**Comment by qiuyaofan** [comment]
```

$('.J-datepicker-range').datePicker({
   hide:function(){
        // 范围选择时
        console.info(this.$input.eq(0).val(), this.$input.eq(1).val())
        // 单个选择时
        // console.info(this.$input.val())
    }
});

```

**Comment by rxliuli** [comment]
有没有某种方式能够全局设置在隐藏后触发 `input` 的 `change` 事件呢？

**Comment by qiuyaofan** [comment]
使用场景是什么

**Comment by rxliuli** [comment]
> 使用场景是什么

主要是使用 `vuejs`（没错，吾辈在传统项目中尝试使用了 `vuejs`）的表单中需要监听表单元素的变化，目前无法绑定 `onchange` 事件，导致每个日期都需要写一个 `initDateSelect` 函数，并在 `hide` 回调中修改 `data` 中的对象，最后使用监听 `watch` 中监听 `data` 的属性。
老实说步骤实在过于麻烦了。。。˞͛꒰๑ऀ •̆ꈊ͒ू•̆๑ऀ꒱

**Comment by qiuyaofan** [comment]
vuejs不如直接用element的datepicker 本来交互就是按照那个做的 element还更好

**Comment by rxliuli** [comment]
没，所以吾辈才特指［传统前端］里面使用 vuejs  (ﾉω･｀o)

kerry <notifications@github.com> 于 2019年3月20日周三 12:07写道：

**Comment by qiuyaofan** [comment]
我看不太懂你说什么。。你要是vue语法，调用了时间插件的input不需要自己绑onchange事件,在hide回调里获取值，每个input加data=“dataname”,在hide里判断去赋值data，不需要最后使用监听 watch 中监听 data 的属性
