### ISSUE TITLE
选择日期之后input元素的value没有变化

### ISSUE THREAD

**Issue by QuinVon** [qiuyaofan/datepicker#10]
如何能够获取选中的日期值呢？

**Comment by qiuyaofan** [comment]
//时分秒年月日范围，包含最大最小值
          $('.J-datepicker-range').datePicker({
            isRange: true,
            hide: function (type) {
              console.info(this.$input.eq(0).val(), this.$input.eq(1).val());
              console.info('类型：',type)
            }
          });

可以在hide函数里获取，因为选完后还有其他操作才去改变val值，你直接获取还没赋值就会是原本的值
