### ISSUE TITLE
火狐在火狐浏览器上面 最大时间的限制和最小事件限制(年月格式的）不起作用

### ISSUE THREAD

**Issue by Deadpool957** [qiuyaofan/datepicker#13]
//年月单个
          $('.J-yearMonthPicker-single').datePicker({
            format: 'YYYY-MM',
            min: '2018-01',
            max: '2019-04'
          });

**Comment by Deadpool957** [comment]
楼主，这个问题解决了吗？我没找到解决的方案

**Comment by qiuyaofan** [comment]
昨天更新所以关闭了 你下载最新的文件 @Deadpool957

**Comment by Deadpool957** [comment]
嗯嗯

**Comment by Deadpool957** [comment]
谢谢楼主，问题解决了
