### ISSUE TITLE
选择完成的回调函数怎么写

### ISSUE THREAD

**Issue by Hyperioon** [qiuyaofan/datepicker#18]
选择完成的回调函数怎么写

**Comment by Hyperioon** [comment]
选择完成的回调函数怎么写

**Comment by qiuyaofan** [comment]
hide回调函数返回type参数, 类型有：choose，confirm，shortcut，clickBody
用法如下：
hide:function(type){   
   if(type==='confirm'){     
       // 点击确定后调用   
  }
}
