### ISSUE TITLE
使用时，可否改变类或标签，有更大的可拓展性

### ISSUE THREAD

**Issue by lilinjuna** [qiuyaofan/datepicker#20]
感谢分享！使用时，只能以div+input的形式出现，并且类名不能改变吗？比如，添加按钮事件

**Comment by qiuyaofan** [comment]
只有div+input的形式，input可以输入，不想输入可以禁掉，更灵活。
类名不能改变是指哪些的类名？html里的可以加，目前picker里渲染出的弹窗里的不能加，如果有场景或需求可以提，考虑实用性决定要不要加

**Comment by lilinjuna** [comment]
类名指的是div+input下的类名，如果改变了类名似乎是不响应的

**Comment by qiuyaofan** [comment]
给实际的在线代码例子，如果是绑定时间选择初始化的类名，要改一起改就可以，如果是带着c-的只是会影响样式而已
