### ISSUE TITLE
年月日选择器没有清空按钮。

### ISSUE THREAD

**Issue by dagger9527** [qiuyaofan/datepicker#25]
![image](https://user-images.githubusercontent.com/30307500/64506576-a00f4600-d30a-11e9-9747-0f3126b65fc2.png)
![image](https://user-images.githubusercontent.com/30307500/64506610-c339f580-d30a-11e9-9d06-34f5d6ebd34a.png)
时间选择器有清空按钮，单选年月日没有清空按钮。

**Comment by qiuyaofan** [comment]
加上单个的也清空按钮了，本来是觉得没必要。
取消的改了宽度，我电脑没重现
