### ISSUE TITLE
Other Format exept YYYY-MM-DD HH:mm:ss not working

### ISSUE THREAD

**Issue by Trickscenique** [qiuyaofan/datepicker#28]
Error : Invalid date on second date select event after dropdown closed once
Todo : API.newDateFixed() should always return a moment and parse _this.config.format
`newDateFixed : function (_this, temp) {
      var result = moment(temp, _this.config.format)
      return result;
}`
Replace all `moment(newDateFixed())` by `newDateFixed()`

**Comment by qiuyaofan** [comment]
which Format you user

**Comment by Trickscenique** [comment]
DD/MM/YYYY and DD/MM/YYYY HH:mm:ss

**Comment by qiuyaofan** [comment]
the order can not change,can only support YYYY/MM/DD ,YYYY/MM/DD HH:mm:ss
