### ISSUE TITLE
来个mobie them就很完美了

### ISSUE THREAD

**Issue by Skull-Li** [qiuyaofan/datepicker#3]
考虑下能不能加个自适应或者mobile选择
谢谢

**Comment by qiuyaofan** [comment]
mobile端不适合这种 直接换滑动选择的 还是你是想在手机端打开pc页面也可以用的意思？

**Comment by Skull-Li** [comment]
有时候肯定在一些特殊情况要处理数据，然后虽然管理端是PC的但是我们通过移动设备访问，能有个稍微友好点的展示形态。
当然如果作者没空，可以考虑能否将界面抽象出来，这样我们可以单独去定制展示形式，也就是所谓的做主题插件。
如果该插件是出于只对pc端考虑的前提可以忽略这issues，像我们因为一些特殊原因，管理端也是做了移动适配的，单独去做一套移动管理端对于我们来说这成本又过于庞大，本身业务也还没到达独立管理端的需求
感谢

**Comment by qiuyaofan** [comment]
如果只是改样式 可以直接改scss文件的 你判断是手机端就加个父类 覆盖部分样式就行
定制展示形式，也就是所谓的做主题插件 这句话没看懂
