### ISSUE TITLE
选择时间的时候，滚不到想要选中的时间

### ISSUE THREAD

**Issue by Nicklzy** [qiuyaofan/datepicker#31]
我看demo里就有这个问题，我一用鼠标滚动，就滚动了好几个小时，比如我现在是14点，我想选15点，结果一滚，就到17点了，时间那边也不能点击15点，一点就关闭窗口了

**Comment by yanbeibei123** [comment]
找到怎么解决了吗，急

**Comment by Nicklzy** [comment]
你给他加上一个滚轮的样式，让鼠标按住滚动条滚动，这样比较精确，可以选中需要的时间

**Comment by Nicklzy** [comment]
> 找到怎么解决了吗，急
你给组件加上一个滚轮的样式，让鼠标按住滚动条滚动，这样比较精确，可以选中需要的时间

**Comment by Nicklzy** [comment]
你给组件加上一个滚轮的样式，让鼠标按住滚动条滚动，这样比较精确，可以选中需要的时间

**Comment by Nicklzy** [comment]
加滚轮样式解决
