### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by songge8** [qiuyaofan/datepicker#7]
时分秒，非十分秒。怪不得感觉别扭

**Comment by elintsun** [comment]
时间弹出框不能点击

**Comment by qiuyaofan** [comment]
时间弹出框不能点击是哪一个？什么配置？什么浏览器等写详细点

**Comment by songge8** [comment]
> 时间弹出框不能点击是哪一个？什么配置？什么浏览器等写详细点

期待大神继续更新，功能和样式都感觉很不错。只是兼容性可能需要提高一下，前几天放到项目里试了一下，有问题出现，就换其他插件了，但是由于试过的插件比较多，记不清具体问题了。如果需要，我可以再重现一下。
还有另外一点有点疑惑，一般日期选择插件绑定元素都是输入框本身，大神为什么要绑定上级元素呢？前端小白。。。

**Comment by qiuyaofan** [comment]
因为有范围选择的情况 绑input不方便 上级元素可以方便兼容两种情况 有空重现的话发下具体的
